### ISSUE TITLE
Error when loading simbench net

### ISSUE THREAD

**Issue by christoph-weyhing** [e2nIEE/simbench#10]
When I run

`net = sb.get_simbench_net('1-EHV-mixed--2-no_sw)`

I get the following error:

Traceback (most recent call last):

  File "c:\users\s792\documents\git_mathenergy_pybench\mathenergy_pybench\master_thesis_christoph\future_scenario_nep_c2030\ptg_instal_conv_gen_net_ext.py", line 30, in <module>
    net_simb = sb.get_simbench_net('1-EHV-mixed--2-no_sw')

  File "c:\users\s792\documents\git_mathenergy_pybench\mathenergy_pybench\simbench\simbench\networks\extract_simbench_grids_from_csv.py", line 367, in get_simbench_net
    net = csv_data2pp(csv_data)

  File "c:\users\s792\documents\git_mathenergy_pybench\mathenergy_pybench\simbench\simbench\converter\csv_pp_converter.py", line 108, in csv_data2pp
    _convert_measurement(csv_data)

  File "c:\users\s792\documents\git_mathenergy_pybench\mathenergy_pybench\simbench\simbench\converter\csv_pp_converter.py", line 412, in _convert_measurement
    data["Measurement"].loc[idx_trafo, "side"] = ["hv" if is_hv else "lv" for is_hv in are_hv]

  File "C:\Users\s792\anaconda3\envs\gitpandapower\lib\site-packages\pandas\core\indexing.py", line 670, in __setitem__
    iloc._setitem_with_indexer(indexer, value)

  File "C:\Users\s792\anaconda3\envs\gitpandapower\lib\site-packages\pandas\core\indexing.py", line 1666, in _setitem_with_indexer
    raise ValueError(

ValueError: cannot set using a multi-index selection indexer with a different length than the value

I got the error for pandas 1.1.3, 1.1.4 and 1.1.5.

**Comment by wangzhenassd** [comment]
I get similar issue with latest pandas version.

**Comment by SteffenMeinecke** [comment]
Sorry for the late response.
Did you notice issue #6? I suggest this is the same issue and should be fixed with simbench version 1.2.0. Please let me know if not.
