### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by JcHdz95** [e2nIEE/simbench#28]
Why I can't install PandaPower?, I follow the instructions of Youtube

(base) C:\Users\4PF96LA_RS6>pip install pandapower
Requirement already satisfied: pandapower in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (2.10.1)
Requirement already satisfied: packaging in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from pandapower) (21.3)
Requirement already satisfied: pandas>=1.0 in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from pandapower) (1.4.4)
Requirement already satisfied: numpy>=0.11 in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from pandapower) (1.21.5)
Requirement already satisfied: tqdm in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from pandapower) (4.64.1)
Requirement already satisfied: deepdiff in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from pandapower) (6.2.1)
Requirement already satisfied: scipy in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from pandapower) (1.9.1)
Requirement already satisfied: networkx>=2.5 in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from pandapower) (2.8.4)
Requirement already satisfied: pytz>=2020.1 in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from pandas>=1.0->pandapower) (2022.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from pandas>=1.0->pandapower) (2.8.2)
Requirement already satisfied: ordered-set<4.2.0,>=4.0.2 in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from deepdiff->pandapower) (4.1.0)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from packaging->pandapower) (3.0.9)
Requirement already satisfied: colorama in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from tqdm->pandapower) (0.4.5)
Requirement already satisfied: six>=1.5 in c:\users\4pf96la_rs6\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas>=1.0->pandapower) (1.16.0)

(base) C:\Users\4PF96LA_RS6>python
Python 3.9.13 (main, Aug 25 2022, 23:51:50) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import pandapower.test
>>> pandapower.test.run_all_tests()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pandapower\test\run_tests.py", line 55, in run_all_tests
    pytest.main([test_dir, "-xs"])
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 145, in main
    config = _prepareconfig(args, plugins)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 324, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_callers.py", line 55, in _multicall
    gen.send(outcome)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\helpconfig.py", line 102, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1016, in pytest_cmdline_parse
    self.parse(args)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1304, in parse
    self._preparse(args, addopts=addopts)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1206, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_hooks.py", line 265, in __call__
    return self._hookexec(self.name, self.get_hookimpls(), kwargs, firstresult)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_manager.py", line 80, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_callers.py", line 60, in _multicall
    return outcome.get_result()
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_result.py", line 60, in get_result
    raise ex[1].with_traceback(ex[2])
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\pluggy\_callers.py", line 39, in _multicall
    res = hook_impl.function(*args)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 1083, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 529, in _set_initial_conftests
    self._try_load_conftest(anchor, namespace.importmode, rootpath)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 551, in _try_load_conftest
    self._getconftestmodules(x, importmode, rootpath)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 575, in _getconftestmodules
    mod = self._importconftest(conftestpath, importmode, rootpath)
  File "C:\Users\4PF96LA_RS6\anaconda3\lib\site-packages\_pytest\config\__init__.py", line 620, in _importconftest
    assert mod not in mods
AssertionError

**Comment by SteffenMeinecke** [comment]
Hi @JcHdz95,
if you got no error while installing pandapower, you usually have pandapower installed successfully. You can check that by typing `pip install pandapower` (a line with a pandapower version is expected).
Then the issue might be that you python doesn't know where to find the packages installed by pip.
If that comment wasn't enough to solve the issue, please open an issue at the [pandapower repo](https://github.com/e2nIEE/pandapower/issues).
