### ISSUE TITLE
error on loadflow with backward forward sweep algorithm on simbench lv rural network

### ISSUE THREAD

**Issue by rahatN-tech** [e2nIEE/simbench#33]
`sb_net = "1-LV-rural1--0-sw"
net = sb.get_simbench_net(sb_net)
pp.runpp(net, algorithm='bfsw')
print(net.res_bus)`

on running the above code , i m getting the following error
Traceback (most recent call last):
  File "d:/python rahat/osman boyaci/pp_try_four.py", line 37, in <module>
    pp.runpp(net, algorithm='bfsw')
  File "C:\Users\Mairah\AppData\Local\Programs\Python\Python37\lib\site-packages\pandapower\run.py", line 232, in runpp
    _powerflow(net, **kwargs)
  File "C:\Users\Mairah\AppData\Local\Programs\Python\Python37\lib\site-packages\pandapower\powerflow.py", line 84, in _powerflow
    result = _run_pf_algorithm(ppci, net["_options"], **kwargs)
  File "C:\Users\Mairah\AppData\Local\Programs\Python\Python37\lib\site-packages\pandapower\powerflow.py", line 162, in _run_pf_algorithm
    result = _run_bfswpf(ppci, options, **kwargs)[0]
  File "C:\Users\Mairah\AppData\Local\Programs\Python\Python37\lib\site-packages\pandapower\pf\run_bfswpf.py", line 408, in _run_bfswpf
    ppci, DLF, buses_ordered_bfs_nets = _get_bibc_bcbv(ppci, options, bus, branch, G)
  File "C:\Users\Mairah\AppData\Local\Programs\Python\Python37\lib\site-packages\pandapower\pf\run_bfswpf.py", line 178, in _get_bibc_bcbv
    DLF, buses_ordered_bfs_nets = _make_bibc_bcbv(bus, branch, graph)
  File "C:\Users\Mairah\AppData\Local\Programs\Python\Python37\lib\site-packages\pandapower\pf\run_bfswpf.py", line 149, in _make_bibc_bcbv
    shape=(nobranch, nobranch))
  File "C:\Users\Mairah\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\sparse\compressed.py", line 54, in __init__
t__
    self._check()
  File "C:\Users\Mairah\AppData\Local\Programs\Python\Python37\lib\site-packages\scipy\sparse\coo.py", line 289, in _check
    raise ValueError('negative column index found')
ValueError: negative column index found

what could be the issue
kindly help

**Comment by SteffenMeinecke** [comment]
related to https://github.com/e2nIEE/pandapower/issues/1072#issuecomment-1587064429
