### ISSUE TITLE
Error loading simbench networks

### ISSUE THREAD

**Issue by DavidEnergie** [e2nIEE/simbench#7]
Hi SimBenchers,

I tried running the [SimBench Tutorial  simbench_grids_basics_and_usage.ipynb ](https://github.com/e2nIEE/simbench/blob/master/tutorials/simbench_grids_basics_and_usage.ipynb), but fail to load any network.

Specifically I ran the Jupyter code **In [19]:** and **In [22]:**.

_pandas                  1.0.3
numpy                     1.18.1 
pandapower            2.2.2
simbench                1.1.0_ 

I get the following error:
**AttributeError: 'pandapowerNet' instance has no attribute 'res_bus'**

` sb_code2 = "1-HVMV-urban-all-0-no_sw"  # urban hv grid with one connected mv grid which has the subnet 2.202
multi_voltage_grid = sb.get_simbench_net(sb_code2)
Traceback (most recent call last):

  File "<ipython-input-30-ca6fc836177d>", line 2, in <module>
    multi_voltage_grid = sb.get_simbench_net(sb_code2)

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/networks/extract_simbench_grids_from_csv.py", line 367, in get_simbench_net
    net = csv_data2pp(csv_data)

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/csv_pp_converter.py", line 127, in csv_data2pp
    _convert_elements_and_types(csv_data, net)

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/csv_pp_converter.py", line 653, in _convert_elements_and_types
    _rename_and_multiply_columns(input_data)

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/csv_pp_converter.py", line 718, in _rename_and_multiply_columns
    to_rename_and_multiply_tuples = _get_parameters_to_rename_and_multiply()

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/csv_pp_converter.py", line 754, in _get_parameters_to_rename_and_multiply
    _prepare_res_bus_table(dummy_net)

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/pp_net_manipulation.py", line 387, in _prepare_res_bus_table
    if net.res_bus.shape[0]:

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/pandapower/auxiliary.py", line 162, in __getattr__
    cls=self.__class__.__name__, name=key

AttributeError: 'pandapowerNet' instance has no attribute 'res_bus'`

Is there a workaround?
Is the issue related to Issue #6 ? 
 
Best wishes

**Comment by DavidEnergie** [comment]
Sorry my fault, I updated and the issue is gone. Arriving at issue #6 

**ValueError: cannot set using a multi-index selection indexer with a different length than the value**
