### ISSUE TITLE
Error loading simbench networks: AttributeError: 'pandapowerNet' instance has no attribute 'res_bus'

### ISSUE THREAD

**Issue by DavidEnergie** [e2nIEE/simbench#8]
Hello again,

after updating to:

_simbench 1.2.0 (from 1.1.0)
pandapower 2.2.2
pandas 1.1.1 (from 1.0.3)
numpy 1.19.1 (1.18.1)_ 

I get almost the same issue as in  #7 

net = sb.get_simbench_net("1-LV-urban6--0-sw")
Traceback (most recent call last):

  File "<ipython-input-2-20c281f29f79>", line 1, in <module>
    net = sb.get_simbench_net("1-LV-urban6--0-sw")

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/networks/extract_simbench_grids_from_csv.py", line 367, in get_simbench_net
    net = csv_data2pp(csv_data)

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/csv_pp_converter.py", line 127, in csv_data2pp
    _convert_elements_and_types(csv_data, net)

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/csv_pp_converter.py", line 660, in _convert_elements_and_types
    _rename_and_multiply_columns(input_data)

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/csv_pp_converter.py", line 725, in _rename_and_multiply_columns
    to_rename_and_multiply_tuples = _get_parameters_to_rename_and_multiply()

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/csv_pp_converter.py", line 761, in _get_parameters_to_rename_and_multiply
    _prepare_res_bus_table(dummy_net)

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/simbench/converter/pp_net_manipulation.py", line 387, in _prepare_res_bus_table
    if net.res_bus.shape[0]:

  File "/home/anaconda3/envs/env_panpow_py37/lib/python3.7/site-packages/pandapower/auxiliary.py", line 162, in __getattr__
    cls=self.__class__.__name__, name=key

AttributeError: 'pandapowerNet' instance has no attribute 'res_bus'

As far as I understand in the function "_prepare_res_bus_table(dummy_net)" the if statement is trying to access net.res_bus, which is not defined/initialised. I can't find a initialisation of the result tables for net.

**Comment by SteffenMeinecke** [comment]
Unfortunately I could not replicate the problem using the following setting:

- Python 3.6.8
- simbench 1.2.0 (as you)
- pandapower 2.2.2 (as you)
- pandas 1.1.1 (as you)
- numpy 1.19.1 (as you)

Apparently no DataFrame named "res_bus" is created in `csv_pp_converter.py` line 759 to `dummy_net` or is removed again in line 760, so that it cannot be accessed in `pp_net_manipulation.py` line 387.

Which python version do you use?
What is the output when you execute the following code?

```
import pandapower as pp
print("res_bus" in pp.create_empty_network().keys())
```

**Comment by SteffenMeinecke** [comment]
no updates so far, closing for now.
